### PR TITLE
Derrick pavia

### PR DESCRIPTION
**Pull request by derrickp1223**
Added wasd movement, and a pause menu with buttons to resume or quit.

### CODE REVIEW

**Review by derrickp1223 — COMMENTED** [review]
Forgot to remove variable from pause_game if statement for better factoring but its okay.

**Review by aidenisaman — APPROVED** [review]
Looks all good to me, keep up the good work.

**Comment by D7RV23** [comment]
Could not see anything wrong from my end, looks fine

**Review by D7RV23 — APPROVED** [review]
forgot to click on approve

**Pull request merged**
