### PR TITLE
Invulnerable when spawning 

### PR DESCRIPTION
**Pull request by derrickp1223**
For two seconds after spawning you are invincible so you don't get killed right when you spawned.

### CODE REVIEW

**Comment by derrickp1223** [comment]
I think your code looks very good and functional you get my approval.

**Comment by derrickp1223** [comment]
This will also merge the change where you no longer respawn in the middle after being hit.

**Review by aidenisaman — APPROVED** [review]
All tests were passed, I can not think of any way to improve upon the code at this moment, all changes make sense and nothing seems bloated/unnecessary.

**Review by D7RV23 — APPROVED** [review]
looks good from my point of view

**Pull request merged**
